import random

class Settings:
    def __init__(self):
        self.horse_stats = {
            'speed': 0,
            'strength': 0,
            'focus': 0,
            'stamina': 0,
            'training': 0,
        }

        self.horse_names = [
            'Amber', 
            'Angel', 
            'Autumn', 
            'Bella',
            'Biscuit', 
            'Blackjack',
            'Blaze', 
            'Bolt',
            'Chance', 
            'Comet', 
            'Daisy', 
            'Delta', 
            'Donkey',
            'Favory', 
            'Hidalgo', 
            'Lightning', 
            'Lucky', 
            'Magnum',
            'Max', 
            'MoonPie',
            'Midnight', 
            'Misty', 
            'Peanut',
            'Penny',
            'Ponyta'
            'Pistol',
            'Pumpkin',
            'Scout', 
            'Shadow', 
            'Spirit',
            'Star', 
            'Storm', 
            'Sunny',
            'Rapidash', 
            'Thor',
            'Thunder', 
            'Willow',
            'Zorro',
        ]

        self.racer_names = [
            'Ellen',
            'John',
            'Sue',
            'Bob',
            'Alice',
            'Tom',
            'Jerry',
            'Mary',
            'Sally',
            'Frank',
            'Jane',
            'Mike',
            'Chris',
            'David',
            'Sam',
            'Steve',
            'Bill',
            'Karen',
            'Nancy',
            'Jill',
            'Kathy',
            'Pam',
            'Ruth',
            'Tina',
            'Wendy',
            'Cathy',
            'Diane',
            'Janet',
            'Robin',
            'Sharon',
            'Cindy',
            'Donna',
            'Debbie',
            'Gloria',
            'Joan',
            'Kelly',
            'Maria',
            'Paula',
            'Peggy',
            'Vicki',
            'Bonnie',
            'Simon',
            'Kenrie',
            'Joe',
            'Joey',
            'Mieke',
            'Bruno',
        ]


    



